apiVersion: v1
kind: Secret
metadata:
  name: docker-credentials
  namespace: tekton-pipelines
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "username": "surajkumar00",
          "password": "dckr_pat_orqtt0yZBTWxyCvyuUZdJK-fXsk",
          "email": "suraj.ukumar.p@gmail.com",
          "auth": "base64-encoded-username:password"
        }
      }
    }
