apiVersion: v1
kind: Secret
metadata:
  name: github-ssh-key
  namespace: tekton-pipelines
type: Opaque
stringData:
  id_rsa: |
    # Replace with your private SSH key
        -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
    NhAAAAAwEAAQAAAgEAlDCJDR7NxH0QH8UaGvUOH6Q8SIcWutHPHGtjru5rBhfDNgjtl65U
    qQGCqFvrFWSDe1CQEIDK6HG6oaf6NK1G3ZswUtrhMmrvxKg3xXgvwGbq4q/pPJ9KKUkeov
    eIn50HyK8VWadAbkiyUvRJFeGGFGun4w/CQvrsuJvFKC/BwZsRMCQGxvPCLzSRi8cxIX7w
    dbXwu5wCvaWdtshWy3lriRdjIZHrjIZOKLFzi4S/PiJjx2eSzgfxrfs2CfqJ9Uu/NcVN0e
    q1vDVpkk2IDabpApLZYdg6hYqOk+QBncQQvhLp0ya7X93hoRjjCQ5VN5TU38tRFzcRAkKQ
    nZV1sQnADY2XUI8MJFHnecPyxkhfPUrP8yZtawaZnPE2vMap169HhOyfbzBBTpl1/1Xmbh
    P6fwBWWJOnREDCl2rqbOXhWftj6YPbEcU+Mb5fBaqQyR9lhRpfJvqEYM5e63gKYa7fhO1B
    v3BDY9KdvQoCBVtybGryX7Ww9J64X4MtTnNdohkzgT8m/ez0v7VLytJ0orz7rjv34M14l1
    GtZ1iYbnzYKo7F8ISsspLDKPdwkYiFwbCWPvEQ4+dzPH1t3CRodiI5MYl6eEgjuwk29KLo
    Y8v6Se7KUoYc5dvDsnhxLvbdVlANmDGNX7rHExvnnOouyMZgKOo/qs2Y/7CBfzK66OgYp8
    EAAAdQQyNpcUMjaXEAAAAHc3NoLXJzYQAAAgEAlDCJDR7NxH0QH8UaGvUOH6Q8SIcWutHP
    HGtjru5rBhfDNgjtl65UqQGCqFvrFWSDe1CQEIDK6HG6oaf6NK1G3ZswUtrhMmrvxKg3xX
    gvwGbq4q/pPJ9KKUkeoveIn50HyK8VWadAbkiyUvRJFeGGFGun4w/CQvrsuJvFKC/BwZsR
    MCQGxvPCLzSRi8cxIX7wdbXwu5wCvaWdtshWy3lriRdjIZHrjIZOKLFzi4S/PiJjx2eSzg
    fxrfs2CfqJ9Uu/NcVN0eq1vDVpkk2IDabpApLZYdg6hYqOk+QBncQQvhLp0ya7X93hoRjj
    CQ5VN5TU38tRFzcRAkKQnZV1sQnADY2XUI8MJFHnecPyxkhfPUrP8yZtawaZnPE2vMap16
    9HhOyfbzBBTpl1/1XmbhP6fwBWWJOnREDCl2rqbOXhWftj6YPbEcU+Mb5fBaqQyR9lhRpf
    JvqEYM5e63gKYa7fhO1Bv3BDY9KdvQoCBVtybGryX7Ww9J64X4MtTnNdohkzgT8m/ez0v7
    VLytJ0orz7rjv34M14l1GtZ1iYbnzYKo7F8ISsspLDKPdwkYiFwbCWPvEQ4+dzPH1t3CRo
    diI5MYl6eEgjuwk29KLoY8v6Se7KUoYc5dvDsnhxLvbdVlANmDGNX7rHExvnnOouyMZgKO
    o/qs2Y/7CBfzK66OgYp8EAAAADAQABAAACAAFbAL9SvQVfTIgSEALHieEL46xSthuNIixP
    g07MTsTHlgn3ren6rq4Jhdyxs3JFIpwy7/A2Gy0IjWFV/Ku+tHVzPY9ndQ+AEAhqaCRKTN
    tq0ZRgRHihDB8mYTu5DaO1a1bSB6nm/E4gV2DuZWzLYAQOLUlxcwvH7FJrhD0+YElFVU4A
    r8I7sVbOhjpX8i6J6pI7RB8omA0sj3QQLAkrzgorEVvmcA5l5AxOHblP959OaX9cOc9gkU
    zMkNypesZlL0o/9a364n2zVx9iOuSSYBYHGl3a6fBsZIp/15lkfu/CWZq2ACxXACqOh5UC
    AurP8olhKUE2XpJL+7MuTmn/qOU1rN6JazFEnWNc+E3z/FeDBt/hcsCoAimTgPbuxM86pH
    HcgHysF0o38Ucp3dAKr7soMZXVITZYaXEtKEeUAKJCi55hjaM1Z77o14ZQUCKuYDNUsG/K
    EMQHDVY9VCsJqe4K0QC0bXBYFJXnlkVoGGdpA9OIUX8VcVp6pwl4std/KRqT7C8FzaqL+e
    DiTMWUOXeDRXhbgmVTxJ3j9XuYPl8juHp8mtRzbo0vPe3qWdJQxiYKC81vu69H4WAIJWXF
    Fi3JnHN9Qy/GUqjOYF2zBtQgehk2HJS8g57JZxx9ltXFdlUuIZw9Nap5LSswYiEZ5O0PvJ
    9CQ8V35DLHveeGbgOxAAABAB1309YlY2tYCGTfd0qKwETId8plzI3jN6NHioXCUP9oEaz8
    /xQ49q+nqkGt6AJSE/DsOzC3TNLJnB4aYLI/eLsJSsi9pcLqreTe6DHowIv1lfR/QYcr3n
    nY0fYjYwB+yzn5kq0rnmtXQ/2RQDmNdi/CYtq/ZqPxTC+DpQ3mfiFXkA9tWkl6n0q31T7v
    99J1B+ZaMqfjrEDjC8itECNFz/LFBm0LycI9Xae9if9qK2W+al6bOz3uOD2fvzYfPFBTmK
    Ja3sgcQsIy4Rm7HwwNtqTW1Buy6kJEnDTkPer4ntKAhEeQKFc2RxuZb53BH+GGUFXSv63f
    0b4TuecMh3/8wJ0AAAEBALs9gqH5b9xdUaijEmTB4RXr6r7ooIsz098PlDjs9SkzT52Gpf
    9mDgOMwgJeaRWo/OlwF5JX6x/rRcWu0vV7RtxX8dYCHHMMUJ4GxRxkdcEdy1w0KIihImdF
    5y5psUzZMxlT4b46XOAgft+zibvADqzgT8RsMLRfxrUl1iiro4My6kGt2PfuVMqWTRS/vI
    O/IBI36qp67Ci37R99lUlWfYhlu3HFSLcnMTBxxh/5uSJdBpblTK6Py5vpKItA4C7Mc+kC
    v1Bj9p/Tc/A12pZMJhDQtV0KdtJD57vsgWVUMMLOg2CTPUvUiXVm5ezJAcmktCeOcQck/P
    tYNlQerxWkrhEAAAEBAMqb3R+bcOmxxl9+LVtVs87KAvtWmofGJ9j6+E3gPtXBkpgNta3D
    Xu9Y7SZx8WGu2RA+/+PEBJl+QeoMmvzWNmeIDoRQeT64M5AUB1YFmEM1LveHeatD0Y5oIv
    LKDsNfq/lk6bWVHeSU2rebLadTY1hB0XIyzTgRtUJ//op1cN5gUV6s5kAe/+VwrFjBTE+w
    wAwm5mn8htFJy2/WWoF5Mgm8iZ2J1B0FgDIX4srdWObEIjIrg0OIxxyb2QaBClg1fHq6CE
    wK+eEn9axBaQo8xeXanXiXgipn5JAjVcA+dOSwNxjXxQo1rrSdZS6ukbKMKytLWX/6Jg0c
    OqMTUpphbrEAAAAYc3VyYWoudWt1bWFyLnBAZ21haWwuY29tAQID
    -----END OPENSSH PRIVATE KEY-----

  id_rsa.pub: |-
    # Replace with your public SSH key
    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCUMIkNHs3EfRAfxRoa9Q4fpDxIhxa60c8ca2Ou7msGF8M2CO2XrlSpAYKoW+sVZIN7UJAQgMrocbqhp/o0rUbdmzBS2uEyau/EqDfFeC/AZurir+k8n0opSR6i94ifnQfIrxVZp0BuSLJS9EkV4YYUa6fjD8JC+uy4m8UoL8HBmxEwJAbG88IvNJGLxzEhfvB1tfC7nAK9pZ22yFbLeWuJF2MhkeuMhk4osXOLhL8+ImPHZ5LOB/Gt+zYJ+on1S781xU3R6rW8NWmSTYgNpukCktlh2DqFio6T5AGdxBC+EunTJrtf3eGhGOMJDlU3lNTfy1EXNxECQpCdlXWxCcANjZdQjwwkUed5w/LGSF89Ss/zJm1rBpmc8Ta8xqnXr0eE7J9vMEFOmXX/VeZuE/p/AFZYk6dEQMKXaups5eFZ+2Ppg9sRxT4xvl8FqpDJH2WFGl8m+oRgzl7reAphrt+E7UG/cENj0p29CgIFW3JsavJftbD0nrhfgy1Oc12iGTOBPyb97PS/tUvK0nSivPuuO/fgzXiXUa1nWJhufNgqjsXwhKyyksMo93CRiIXBsJY+8RDj53M8fW3cJGh2IjkxiXp4SCO7CTb0ouhjy/pJ7spShhzl28OyeHEu9t1WUA2YMY1fuscTG+ec6i7IxmAo6j+qzZj/sIF/Mrro6BinwQ== suraj.ukumar.p@gmail.com
  known_hosts: |-
    # Add GitHub to known hosts
    github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
