apiVersion: v1
kind: Secret
metadata:
  name: github-credentials
  namespace: tekton-pipelines
  annotations:
    tekton.dev/git-0: https://github.com
type: kubernetes.io/basic-auth
stringData:
  username: Suraj-kumar00
  password: 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
