apiVersion: v1
kind: Secret
metadata:
  name: github-credentials
  namespace: tekton-pipelines
  annotations:
    tekton.dev/git-0: https://github.com
    tekton.dev/git-1: github.com
    tekton.dev/git-2: git@github.com
    tekton.dev/git-3: https://github.com/Suraj-kumar00/blog-app-menifests.git
    tekton.dev/git-4: https://github.com/Suraj-kumar00/blog-app-gitops.git
  labels:
    app.kubernetes.io/managed-by: tekton-pipelines
    app.kubernetes.io/component: credentials
    app.kubernetes.io/name: github-credentials
    app.kubernetes.io/part-of: blog-app-pipeline
type: kubernetes.io/basic-auth
stringData:
  username: Suraj-kumar00
  password: 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
