apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: blog-app-pipeline-run-
  namespace: tekton-pipelines
spec:
  pipelineRef:
    name: blog-app-pipeline
  taskRunTemplate:
    serviceAccountName: pipeline-account
    podTemplate:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: docker-credentials
      secret:
        secretName: docker-credentials
    - name: basic-auth
      secret:
        secretName: github-credentials
  params:
    - name: git-url
      value: https://github.com/Suraj-kumar00/blog-app-gitops.git
    - name: image-name
      value: surajkumar00/blog-app
    - name: gitops-repo
      value: https://github.com/Suraj-kumar00/blog-app-menifests.git
