apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-account
  namespace: tekton-pipelines
secrets:
  - name: docker-credentials
  - name: github-credentials
imagePullSecrets:
  - name: docker-credentials
