apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-account
  namespace: tekton-pipelines
secrets:
  - name: github-ssh-key
  - name: docker-credentials
imagePullSecrets:
  - name: docker-credentials
