apiVersion: v1
kind: Secret
metadata:
  name: blog-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/Suraj-kumar00/blog-app-menifests.git
  username: Suraj-kumar00
  password: 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
